# Generated by Django 4.1.2 on 2024-07-12 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videojuego',
            name='fecha_lanzamiento',
        ),
    ]
